application: situation-staging
version: 3
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "12h"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /twitter/post
  script: main.app
  secure: always
  login: admin
  auth_fail_action: unauthorized

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"
